/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IcSignin {
        "config": Record<string, string>;
        "i18n": Record<string, Record<string, string>>;
        "signInError": (err?: string) => void;
        "signInSuccess": () => void;
    }
}
declare global {
    interface HTMLIcSigninElement extends Components.IcSignin, HTMLStencilElement {
    }
    var HTMLIcSigninElement: {
        prototype: HTMLIcSigninElement;
        new (): HTMLIcSigninElement;
    };
    interface HTMLElementTagNameMap {
        "ic-signin": HTMLIcSigninElement;
    }
}
declare namespace LocalJSX {
    interface IcSignin {
        "config"?: Record<string, string>;
        "i18n"?: Record<string, Record<string, string>>;
        "onDdgSignInError"?: (event: CustomEvent<string | undefined>) => void;
        "onDdgSignInSuccess"?: (event: CustomEvent<void>) => void;
        "onInProgress"?: (event: CustomEvent<boolean>) => void;
        "signInError"?: (err?: string) => void;
        "signInSuccess"?: () => void;
    }
    interface IntrinsicElements {
        "ic-signin": IcSignin;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ic-signin": LocalJSX.IcSignin & JSXBase.HTMLAttributes<HTMLIcSigninElement>;
        }
    }
}
